CREATE TABLE Member_Role_Bridge (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '회원권한브릿지아이디',
    member_id BIGINT UNSIGNED NOT NULL UNIQUE COMMENT '회원 아이디',
    role_id BIGINT UNSIGNED NOT NULL UNIQUE COMMENT '권한 아이디',
    FOREIGN KEY (member_id) REFERENCES Member(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (role_id) REFERENCES Role(id) ON UPDATE CASCADE ON DELETE RESTRICT
) COMMENT '회원 권한 브릿지 테이블';

INSERT INTO Member_Role_Bridge (member_id, role_id) VALUES (1, 1);